/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author ismal
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public Image getIconImage() {
        Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/1.png"));
        return retvalue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jApPaterno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jApMaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDia = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jMes = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jGenero = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jEntidad = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jCurpFinal = new javax.swing.JTextField();
        jGenerar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jAnio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jobligatorio1 = new javax.swing.JLabel();
        jobligatorio2 = new javax.swing.JLabel();
        jobligatorio3 = new javax.swing.JLabel();
        jobligatorio5 = new javax.swing.JLabel();
        jfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jsalir.setBackground(new java.awt.Color(255, 255, 255));
        jsalir.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jsalir.setForeground(new java.awt.Color(0, 0, 0));
        jsalir.setText("SALIR");
        jsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalirActionPerformed(evt);
            }
        });
        getContentPane().add(jsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 630, 120, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NOMBRE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, 40));

        jNombre.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jNombre.setForeground(new java.awt.Color(0, 0, 0));
        jNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNombreKeyTyped(evt);
            }
        });
        getContentPane().add(jNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 180, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("AP.PATERNO: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 120, 40));

        jApPaterno.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jApPaterno.setForeground(new java.awt.Color(0, 0, 0));
        jApPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jApPaternoKeyTyped(evt);
            }
        });
        getContentPane().add(jApPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 190, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("AP.MATERNO: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 130, 40));

        jApMaterno.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jApMaterno.setForeground(new java.awt.Color(0, 0, 0));
        jApMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jApMaternoKeyTyped(evt);
            }
        });
        getContentPane().add(jApMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 190, 40));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ESCRIBE TUS DATOS EN MAYUSCULAS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 340, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("FECHA DE NACIMIENTO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 210, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("DD: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jDia.setBackground(new java.awt.Color(255, 255, 255));
        jDia.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jDia.setForeground(new java.awt.Color(0, 0, 0));
        jDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(jDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 60, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("MM: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        jMes.setBackground(new java.awt.Color(255, 255, 255));
        jMes.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jMes.setForeground(new java.awt.Color(0, 0, 0));
        jMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(jMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 60, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("AA:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("SEXO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, -1));

        jGenero.setBackground(new java.awt.Color(255, 255, 255));
        jGenero.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jGenero.setForeground(new java.awt.Color(0, 0, 0));
        jGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "H", "M" }));
        getContentPane().add(jGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 60, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("ENTIDAD ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, -1, -1));

        jEntidad.setBackground(new java.awt.Color(255, 255, 255));
        jEntidad.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jEntidad.setForeground(new java.awt.Color(0, 0, 0));
        jEntidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Coahuila", "Colima", "Chiapas", "Chihuahua", "Ciudad de Mexico", "Durango", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Estado de Mexico", "Michoacan", "Morelos", "Nayarit", "Nuevo Leon", "Oaxaca", "Puebla", "Queretaro", "Quintana Roo", "San Luis Potosi", "Sinaloa", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatan", "Zacatecas", "Extranjero" }));
        getContentPane().add(jEntidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 180, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("CURP: ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, -1, -1));

        jCurpFinal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCurpFinal.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jCurpFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 440, 50));

        jGenerar.setBackground(new java.awt.Color(255, 255, 255));
        jGenerar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jGenerar.setForeground(new java.awt.Color(0, 0, 0));
        jGenerar.setText("GENERAR");
        jGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(jGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, 130, 50));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("En caso de no tener apellido paterno o materno coloca \"XX\"");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        jAnio.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jAnio.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 80, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hombre-y-mujer.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 50, 50));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("LIMPIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 110, -1, -1));

        jobligatorio1.setBackground(new java.awt.Color(255, 255, 255));
        jobligatorio1.setForeground(new java.awt.Color(0, 0, 0));
        jobligatorio1.setText("*OBLIGATORIO");
        getContentPane().add(jobligatorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jobligatorio2.setBackground(new java.awt.Color(255, 255, 255));
        jobligatorio2.setForeground(new java.awt.Color(0, 0, 0));
        jobligatorio2.setText("*OBLIGATORIO");
        getContentPane().add(jobligatorio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        jobligatorio3.setBackground(new java.awt.Color(255, 255, 255));
        jobligatorio3.setForeground(new java.awt.Color(0, 0, 0));
        jobligatorio3.setText("*OBLIGATORIO");
        getContentPane().add(jobligatorio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, -1, -1));

        jobligatorio5.setBackground(new java.awt.Color(255, 255, 255));
        jobligatorio5.setForeground(new java.awt.Color(0, 0, 0));
        jobligatorio5.setText("*OBLIGATORIO");
        getContentPane().add(jobligatorio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        jfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/480p.jpg"))); // NOI18N
        getContentPane().add(jfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//*******************************************************************************************************
//*******************************************************************************************************
    String nombre,apPat,apMat,homoclave,curpf,genero,DD,MM,AA,Fecha,Entidad,veri = "0",veri_dos;
    private void jsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jsalirActionPerformed

    private void jNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNombreKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'A' || c > 'Z') && (c != ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_jNombreKeyTyped

    private void jApPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jApPaternoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'A' || c > 'Z') && (c != ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_jApPaternoKeyTyped

    private void jApMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jApMaternoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'A' || c > 'Z') && (c != ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_jApMaternoKeyTyped

    private void jGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenerarActionPerformed
        //caluclamos todo
         nombre = jNombre.getText();
         apPat = jApPaterno.getText();
         apMat = jApMaterno.getText();
         if(checa() == true){
         nombre += "X";
        nombre = nPila(nombre);                     //verificamos si el nombre esta dentro de los nombre comunes
        genero = jGenero.getSelectedItem().toString();
        homoclave = homoclave(nombre, apPat, apMat);
        curpf = primerLetra(nombre,apMat,apPat);
        DD = jDia.getSelectedItem().toString();
        MM = jMes.getSelectedItem().toString();
        AA = jAnio.getText();
        Entidad = jEntidad.getSelectedItem().toString();
        Entidad = Entidad(Entidad);
        int dd,mm,aa;
        dd = Integer.parseInt(DD);
        mm = Integer.parseInt(MM);
        aa = Integer.parseInt(AA);
        if(mes(mm,dd,aa) == 1){
            Fecha = fecha(AA,MM,DD);
            veri_dos = genera();
       jCurpFinal.setText(curpf+Fecha+genero+Entidad+homoclave+veri+veri_dos);
        }else
            JOptionPane.showMessageDialog(null,"FECHA INCORRECTA");
         }else{
             
         }
    }//GEN-LAST:event_jGenerarActionPerformed

    public boolean checa(){
        if(nombre.equals("")){
        jobligatorio1.setVisible(true);
        return false;
        }else{ 
            jobligatorio1.setVisible(false);
        }
        if(apPat.equals("")){
        jobligatorio2.setVisible(true);
        return false;
        }else{ 
            jobligatorio2.setVisible(false);
        }
        if(apMat.equals("")){
        jobligatorio3.setVisible(true);
        return false;
        }else{ 
            jobligatorio3.setVisible(false);
        }
        if(jAnio.equals("")){
        jobligatorio5.setVisible(true);
        return false;
        }else{ 
            jobligatorio5.setVisible(false);
        }
        return true;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jNombre.setText(null);
        jApPaterno.setText(null);
        jApMaterno.setText(null);
        jAnio.setText(null);
        jCurpFinal.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    public String nPila(String hola) {
        //validar si el nombre es jose o maria 
        //y validar si tiene un segundo nombre
        String nueva = null, separa, aux = null;
        int tam = hola.length(), a = 0;
        separa = hola.substring(0, 4);
        if (separa.equals("JOSE") && tam > 6) {
            aux = hola.substring(5, 7);
            if (aux.equals("DE")) {
                aux = hola.substring(5, 10);
                if (aux.equals("DE LA")) {
                    nueva = hola.substring(11, tam);
                } else {
                    nueva = hola.substring(8, tam);
                }
            } else {
                nueva = hola.substring(5, tam);
            }
        } else if (separa.equals("JOSE") && tam == 4) {
            return hola;
        } else {
            separa = hola.substring(0, 5);
            if (separa.equals("MARIA") && tam > 7) {
                aux = hola.substring(6, 8);
                if (aux.equals("DE")) {
                    aux = hola.substring(6, 11);
                    if (aux.equals("DE LA")) {
                        nueva = hola.substring(12, tam);
                    } else {
                        nueva = hola.substring(9, tam);
                    }
                } else {
                    nueva = hola.substring(6, tam);
                }
            } else if (hola.equals("MARIA") && tam == 5) {
                return hola;
            }
        }
        if (nueva != null) {
            return nueva;
        } else {
            return hola;
        }
    }
    int a = 1, b = 2;
    String letra;
    char nom, ap_p, ap_m;

    public String homoclave(String nombre, String apellido_paterno, String apellido_materno) {
        ap_p = apellido_paterno.charAt(b - 1); //calcula la homoclave 
        ap_m = apellido_materno.charAt(b - 1);
        nom = nombre.charAt(b - 1);
        while (checa(ap_p) == 0) { //checamos apellido paterno
            ap_p = apellido_paterno.charAt(b - 1);
        }
        letra = apellido_paterno.substring(a, b);
        a = 1; //checamos apellido materno
        b = 2;
        while (checa(ap_m) == 0) {
            ap_m = apellido_materno.charAt(b - 1);
        }
        letra = apellido_materno.substring(a, b);
        a = 1; //checamos nombre
        b = 2;
        while (checa(nom) == 0) {
            nom = nombre.charAt(b - 1);
        }
        letra = nombre.substring(a, b);
        String ape_pa = Character.toString(ap_p);
        String ape_ma = Character.toString(ap_m);
        String nombr = Character.toString(nom);
        letra = ape_pa + ape_ma + nombr;
        return letra;
    }

    public int checa(char caracter) { // apoyo para metodo homoclave
        if (caracter == 'A' || caracter == 'E' || caracter == 'I' || caracter == 'O' || caracter == 'U' || caracter == ' ') {
            a++;
            b++;
        } else {
            return 1;
        }
        return 0;
    }
    
       public String primerLetra(String nombre,String apellido_mate,String apellido_pate){ 
       String letras,mate,pate,pate_tres,fin = null; 
       /**
        * este metodo sirve para conseguir las primeras letras del apellido paterno, primer letra del materno
        * y nombre, al final regresa todo 
        */
       char pate_dos = 0;
       int d = 2;
       letras = nombre.substring(0,1);
      mate = apellido_mate.substring(0,1);
      
      pate = apellido_pate.substring(0,1);
      pate_tres = primeraVocal(apellido_pate);
      fin = pate+pate_tres + mate + letras;
      return fin;
   }
   public String primeraVocal(String s){    //extraemos primer vocal 
       char []vocales = {'A','E','I','O','U'};
       char palabra;
       String letra;
       int i;
         for(i = 0;i < s.length();i++){
             for(int j = 0;j < vocales.length;j++){
                 palabra = s.charAt(i+1);
                 if(palabra == vocales[j]){
                    letra =  Character.toString(palabra); 
                     return letra;
                 }
             }
         }
        
return null;
   }
   
      public String fecha ( String a, String m, String d){ //junta los datos de la fecha y regresa como String 
	String fecha;
        fecha = a.substring(2,4)+m+d;
	return fecha;
}

      public int mes(int mes,int dias,int anio){ //valida que mes ingreso el usuario y si los dias son correctos 
        switch (mes) {
            case 1:
            case 3:
            case 5:
            case 7:
            case 8:
            case 10:
            case 12:           mes = 1;                break;
            case 4:
            case 6:
            case 9:
            case 11:           mes = 2;                break;
            case 2:
                if ((anio % 4 == 0 && anio % 100 != 0) || anio % 400 == 0) 
                    dias = 2;
                    else 
                    dias = 28;
                mes = 3;
                break;
            default:
                System.out.println("El mes que introdujiste es incorrecto");
                break;      
        }
        if(mes == 1){
            if(dias > 0 && dias <= 31)
                    return 1;
            else 
                return 2;
        }else if(mes == 2){
            if(dias > 0 && dias <= 30)
                return 1;
            else 
                return 2;
        }else if(mes == 3){
            if(dias > 0 && dias <= 28 || dias > 0 && dias <= 29)
                return 1;
            else 
                return 0;
        }
    return 0;
   }
      
      public String Entidad(String ciudad){
          String Ent = null;
          if(ciudad.equals("Aguascalientes"))
              Ent = "AS";
          else if(ciudad.equals("Baja California"))
              Ent = "BC";
          else if(ciudad.equals("Baja California Sur"))
              Ent = "BS";
          else if(ciudad.equals("Campeche"))
              Ent = "CC";
          else if(ciudad.equals("Coahuila"))
              Ent = "CL";
          else if(ciudad.equals("Colima"))
              Ent = "CM";
          else if(ciudad.equals("Chiapas"))
              Ent = "CS";
          else if(ciudad.equals("Chihuahua"))
              Ent = "CH";
          else if(ciudad.equals("Ciudad de Mexico"))
              Ent = "DF";
          else if(ciudad.equals("Durango"))
              Ent = "DG";
          else if(ciudad.equals("Guanajuato"))
              Ent = "GT";
          else if(ciudad.equals("Guerrero"))
              Ent = "GR";
          else if(ciudad.equals("Hidalgo"))
              Ent = "HG";
          else if(ciudad.equals("Jalisco"))
              Ent = "JC";
          else if(ciudad.equals("Estado de Mexico"))
              Ent = "MC";
          else if(ciudad.equals("Michoacan"))
              Ent = "MN";
          else if(ciudad.equals("Morelos"))
              Ent = "MS";
          else if(ciudad.equals("Nayarit"))
              Ent = "NT";
          else if(ciudad.equals("Nuevo Leon"))
              Ent = "NL";
          else if(ciudad.equals("Oaxaca"))
              Ent = "OC";
          else if(ciudad.equals("Puebla"))
              Ent = "PL";
          else if(ciudad.equals("Queretaro"))
              Ent = "QT";
          else if(ciudad.equals("Quintana Roo"))
              Ent = "QR";
          else if(ciudad.equals("San Luis Potosi"))
              Ent = "SP";
          else if(ciudad.equals("Sinaloa"))
              Ent = "SL";
          else if(ciudad.equals("Sonora"))
              Ent = "SR";
          else if(ciudad.equals("Tabasco"))
              Ent = "TC";
          else if(ciudad.equals("Tamaulipas"))
              Ent = "TS";
          else if(ciudad.equals("Tlaxcala"))
              Ent = "TL";
          else if(ciudad.equals("Veracruz"))
              Ent = "VZ";
          else if(ciudad.equals("Yucatan"))
              Ent = "YN";
          else if(ciudad.equals("Zacatecas"))
              Ent = "ZS";
          else if(ciudad.equals("Extranjero"))
              Ent = "NE";
          return Ent;
      }
      
      public String genera(){ //metodo que genera numero verificador al azar 
       int n;
       String num;
       n = (int)(Math.random()*9);
       num = Integer.toString(n);
       return num; 
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAnio;
    private javax.swing.JTextField jApMaterno;
    private javax.swing.JTextField jApPaterno;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jCurpFinal;
    private javax.swing.JComboBox<String> jDia;
    private javax.swing.JComboBox<String> jEntidad;
    private javax.swing.JButton jGenerar;
    private javax.swing.JComboBox<String> jGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jMes;
    private javax.swing.JTextField jNombre;
    private javax.swing.JLabel jfondo;
    private javax.swing.JLabel jobligatorio1;
    private javax.swing.JLabel jobligatorio2;
    private javax.swing.JLabel jobligatorio3;
    private javax.swing.JLabel jobligatorio5;
    private javax.swing.JButton jsalir;
    // End of variables declaration//GEN-END:variables
}
